# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-19 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StarWars', '0002_auto_20180819_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planets',
            name='movie_title',
        ),
    ]
